apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ssh-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-ssh-server
  template:
    metadata:
      labels:
        app: k8s-ssh-server
    spec:
      serviceAccountName: k8s-ssh-sa
      containers:
      - name: k8s-ssh-server
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
        ports:
        - containerPort: 2222
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        - name: KUBECONFIG
          value: /root/.kube/config
        volumeMounts:
        - mountPath: /root/.kube
          name: kubeconfig-volume
      volumes:
      - name: kubeconfig-volume
        configMap:
          name: kubeconfig