apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssh-server-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssh-server-rolebinding
subjects:
- kind: ServiceAccount
  name: k8s-ssh-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ssh-server-role
  apiGroup: rbac.authorization.k8s.io
