apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssh-server-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ssh-server-rolebinding
subjects:
- kind: ServiceAccount
  name: k8s-ssh-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ssh-server-role
  apiGroup: rbac.authorization.k8s.io