apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eks-pod-management-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: k8s-ssh-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: eks-pod-management-role
  apiGroup: rbac.authorization.k8s.io
